name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main    # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main    # Trigger on pull requests targeting the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image to run the jobs

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'  # Specify the version of Terraform you want to use

      # Step 3: Set up AWS credentials (via GitHub Secrets)
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Set in GitHub Secrets
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Set in GitHub Secrets
          aws_region: us-east-1  # Specify the AWS region



      # Step 5: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 6: Plan Terraform deployment
      - name: Terraform Plan
        run: terraform plan -out=plan.tfplan

      # Step 7: Apply Terraform configuration (only on main branch push)
      - name: Terraform Apply
        run: terraform apply -auto-approve plan.tfplan
        if: github.ref == 'refs/heads/main'

